#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export HW_CBMC_TIMEOUT_SEC="${HW_CBMC_TIMEOUT_SEC:-600}"

tests=(
  "axi_id_shape"
  "axi_beat_shape"
  "axi_mode2_shape"
  "axi_pending_scan"
  "axi_issue_select"
  "axi_fifo_ptr"
  "axi_queue_ctrl"
  "axi_write_pack"
  "axi_write_pack_prod_width"
  "axi_read_pack"
  "axi_read_pack_prod_width"
  "bridge_prod_width_cacheline_aw_shape"
  "bridge_prod_width_cacheline_ar_shape"
  "bridge_prod_width_cacheline_write_shape"
  "bridge_prod_width_cacheline_read_response"
  "dual_bridge_prod_width_cacheline_ar_shape"
  "dual_bridge_prod_width_cacheline_read_response"
  "dual_bridge_prod_width_bypass_cacheline_read_response"
  "dual_bridge_prod_width_cacheline_write_shape"
  "dual_bridge_prod_width_mode2_write"
  "dual_bridge_prod_width_ddr_read_mmio_read_independent"
  "dual_bridge_prod_width_ddr_read_mmio_write_independent"
  "dual_bridge_prod_width_ddr_write_mmio_read_independent"
  "dual_bridge_prod_width_ddr_write_mmio_write_independent"
  "dual_bridge_prod_width_same_line_read_blocks_write"
  "dual_bridge_prod_width_same_line_write_blocks_read"
  "axi_read_resp_ctrl"
  "axi_req_accept"
  "axi_resp_accept"
  "axi_resp_route"
  "axi_source_resp_mux"
  "dual_port_issue_gate"
  "dual_port_hazard_match"
  "dual_port_slot_hazard"
  "dual_port_hazard_scoreboard"
  "dual_port_hazard_scoreboard_one_entry"
  "dual_port_req_steer"
  "dual_port_resp_mux"
  "dual_port_route_shape"
  "cache_ctrl_dirty_evict_writeback"
  "cache_ctrl_partial_write_miss_refill"
  "cache_ctrl_read_miss_refill_response"
  "cache_ctrl_partial_write_hit_merge"
  "dual_bridge_read_route"
  "dual_bridge_read_r_response"
  "dual_bridge_write_route"
  "dual_bridge_write_b_response"
  "dual_bridge_ddr_multibeat_read"
  "dual_bridge_ddr_multibeat_write"
  "dual_bridge_same_line_read_blocks_write"
  "dual_bridge_same_line_write_blocks_read"
  "dual_bridge_multi_read_outstanding"
  "dual_bridge_read_then_write_outstanding"
  "dual_bridge_write_then_read_outstanding"
  "dual_bridge_mode2_aligned_write"
  "dual_bridge_mode2_aligned_read"
  "subsystem_dual_mmio_read_route"
  "subsystem_dual_mmio_read_response"
  "subsystem_dual_mmio_write_route"
  "subsystem_dual_mmio_write_response"
  "subsystem_dual_ddr_read_mmio_write_independent"
  "subsystem_dual_cache_refill_mmio_read_independent"
  "subsystem_dual_cache_refill_mmio_write_independent"
  "subsystem_dual_cache_refill_response"
  "subsystem_dual_cache_fill_hit_response"
  "subsystem_dual_cache_full_write_hit_response"
  "subsystem_dual_mode0_ddr_bypass_align"
  "subsystem_dual_mode0_ddr_bypass_read_response"
  "subsystem_dual_mode0_ddr_bypass_read_response_8b"
  "subsystem_dual_cache_dirty_evict_writeback"
  "subsystem_dual_cache_dirty_evict_b_response"
  "subsystem_dual_cache_dirty_evict_post_b_hit"
)

passed=0
for test_name in "${tests[@]}"; do
  printf 'RUN %s\n' "${test_name}"
  "${script_dir}/${test_name}/run_hw_cbmc.sh"
  passed=$((passed + 1))
  printf 'PASS %s\n' "${test_name}"
done

printf 'SUMMARY total=%d passed=%d failed=0\n' "${#tests[@]}" "${passed}"
