module axi_dual_port_hazard_scoreboard_one_entry_formal_top(
    input        clk,
    input        rst_n,
    input  [1:0] ddr_ar_line,
    input  [1:0] mmio_ar_line,
    input  [1:0] ddr_aw_line,
    input  [1:0] mmio_aw_line,
    input  [1:0] ddr_arid,
    input  [1:0] mmio_arid,
    input  [1:0] ddr_awid,
    input  [1:0] mmio_awid,
    input  [1:0] ddr_rid,
    input  [1:0] mmio_rid,
    input  [1:0] ddr_bid,
    input  [1:0] mmio_bid,
    input        ddr_ar_fire,
    input        mmio_ar_fire,
    input        ddr_aw_fire,
    input        mmio_aw_fire,
    input        ddr_r_fire,
    input        mmio_r_fire,
    input        ddr_b_fire,
    input        mmio_b_fire,
    output       ddr_ar_slot_hazard,
    output       mmio_ar_slot_hazard,
    output       ddr_aw_slot_hazard,
    output       mmio_aw_slot_hazard,
    output       ddr_aw_pending_read_hazard,
    output       mmio_aw_pending_read_hazard,
    output       ddr_ar_pending_write_hazard,
    output       mmio_ar_pending_write_hazard
);

    axi_llc_dual_port_hazard_scoreboard #(
        .LINE_TAG_BITS(2),
        .HAZARD_AXI_ID_BITS(2),
        .READ_HAZARD_COUNT(1),
        .WRITE_HAZARD_COUNT(1)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .ddr_ar_line(ddr_ar_line),
        .mmio_ar_line(mmio_ar_line),
        .ddr_aw_line(ddr_aw_line),
        .mmio_aw_line(mmio_aw_line),
        .ddr_arid(ddr_arid),
        .mmio_arid(mmio_arid),
        .ddr_awid(ddr_awid),
        .mmio_awid(mmio_awid),
        .ddr_rid(ddr_rid),
        .mmio_rid(mmio_rid),
        .ddr_bid(ddr_bid),
        .mmio_bid(mmio_bid),
        .ddr_ar_fire(ddr_ar_fire),
        .mmio_ar_fire(mmio_ar_fire),
        .ddr_aw_fire(ddr_aw_fire),
        .mmio_aw_fire(mmio_aw_fire),
        .ddr_r_fire(ddr_r_fire),
        .mmio_r_fire(mmio_r_fire),
        .ddr_b_fire(ddr_b_fire),
        .mmio_b_fire(mmio_b_fire),
        .ddr_ar_slot_hazard(ddr_ar_slot_hazard),
        .mmio_ar_slot_hazard(mmio_ar_slot_hazard),
        .ddr_aw_slot_hazard(ddr_aw_slot_hazard),
        .mmio_aw_slot_hazard(mmio_aw_slot_hazard),
        .ddr_aw_pending_read_hazard(ddr_aw_pending_read_hazard),
        .mmio_aw_pending_read_hazard(mmio_aw_pending_read_hazard),
        .ddr_ar_pending_write_hazard(ddr_ar_pending_write_hazard),
        .mmio_ar_pending_write_hazard(mmio_ar_pending_write_hazard)
    );

endmodule
