module axi_queue_ctrl_formal_top(
    input  [7:0] rd_issue_count,
    input  [7:0] wr_aw_count,
    input  [7:0] wr_w_count,
    input  [7:0] cache_rd_rsp_count,
    input  [7:0] bypass_rd_rsp_count,
    input  [7:0] cache_wr_rsp_count,
    input  [7:0] bypass_wr_rsp_count,
    input        accept_cache,
    input        accept_bypass,
    input        accept_write,
    input        rd_issue_valid,
    input        axi_arready,
    input        wr_aw_valid,
    input        axi_awready,
    input        wr_w_valid,
    input        axi_wready,
    input        axi_wlast,
    output       rd_issue_space,
    output       wr_aw_space,
    output       wr_w_space,
    output       cache_rd_rsp_valid,
    output       bypass_rd_rsp_valid,
    output       cache_wr_rsp_valid,
    output       bypass_wr_rsp_valid,
    output       cache_rd_rsp_space,
    output       bypass_rd_rsp_space,
    output       cache_wr_rsp_space,
    output       bypass_wr_rsp_space,
    output       rd_issue_handshake,
    output       wr_aw_handshake,
    output       wr_w_handshake,
    output       rd_issue_push,
    output       rd_issue_pop,
    output       wr_aw_push,
    output       wr_aw_pop,
    output       wr_w_push,
    output       wr_w_pop
);

    axi_llc_axi_queue_ctrl #(
        .READ_DEPTH(4),
        .WRITE_DEPTH(4)
    ) dut (
        .rd_issue_count(rd_issue_count),
        .wr_aw_count(wr_aw_count),
        .wr_w_count(wr_w_count),
        .cache_rd_rsp_count(cache_rd_rsp_count),
        .bypass_rd_rsp_count(bypass_rd_rsp_count),
        .cache_wr_rsp_count(cache_wr_rsp_count),
        .bypass_wr_rsp_count(bypass_wr_rsp_count),
        .accept_cache(accept_cache),
        .accept_bypass(accept_bypass),
        .accept_write(accept_write),
        .rd_issue_valid(rd_issue_valid),
        .axi_arready(axi_arready),
        .wr_aw_valid(wr_aw_valid),
        .axi_awready(axi_awready),
        .wr_w_valid(wr_w_valid),
        .axi_wready(axi_wready),
        .axi_wlast(axi_wlast),
        .rd_issue_space(rd_issue_space),
        .wr_aw_space(wr_aw_space),
        .wr_w_space(wr_w_space),
        .cache_rd_rsp_valid(cache_rd_rsp_valid),
        .bypass_rd_rsp_valid(bypass_rd_rsp_valid),
        .cache_wr_rsp_valid(cache_wr_rsp_valid),
        .bypass_wr_rsp_valid(bypass_wr_rsp_valid),
        .cache_rd_rsp_space(cache_rd_rsp_space),
        .bypass_rd_rsp_space(bypass_rd_rsp_space),
        .cache_wr_rsp_space(cache_wr_rsp_space),
        .bypass_wr_rsp_space(bypass_wr_rsp_space),
        .rd_issue_handshake(rd_issue_handshake),
        .wr_aw_handshake(wr_aw_handshake),
        .wr_w_handshake(wr_w_handshake),
        .rd_issue_push(rd_issue_push),
        .rd_issue_pop(rd_issue_pop),
        .wr_aw_push(wr_aw_push),
        .wr_aw_pop(wr_aw_pop),
        .wr_w_push(wr_w_push),
        .wr_w_pop(wr_w_pop)
    );

endmodule
