`timescale 1ns / 1ps

// DC-only wrapper for the production DDR-side single AXI bridge shape used by
// axi_llc_axi_bridge_dual: 64B cache lines, 256-bit AXI beats, 32 read/write
// pending slots.
module axi_llc_axi_bridge_ddr64_probe (
    input           clk,
    input           rst_n,
    input           cache_req_valid,
    output          cache_req_ready,
    input           cache_req_write,
    input  [31:0]   cache_req_addr,
    input  [5:0]    cache_req_id,
    input  [7:0]    cache_req_size,
    input  [511:0]  cache_req_wdata,
    input  [63:0]   cache_req_wstrb,
    output          cache_resp_valid,
    input           cache_resp_ready,
    output [511:0]  cache_resp_rdata,
    output [5:0]    cache_resp_id,
    output [1:0]    cache_resp_code,
    input           bypass_req_valid,
    output          bypass_req_ready,
    input           bypass_req_write,
    input  [31:0]   bypass_req_addr,
    input  [5:0]    bypass_req_id,
    input  [7:0]    bypass_req_size,
    input           bypass_req_mode2_ddr_aligned,
    input  [511:0]  bypass_req_wdata,
    input  [63:0]   bypass_req_wstrb,
    output          bypass_resp_valid,
    input           bypass_resp_ready,
    output [511:0]  bypass_resp_rdata,
    output [5:0]    bypass_resp_id,
    output [1:0]    bypass_resp_code,
    output          axi_awvalid,
    input           axi_awready,
    output [5:0]    axi_awid,
    output [31:0]   axi_awaddr,
    output [7:0]    axi_awlen,
    output [2:0]    axi_awsize,
    output [1:0]    axi_awburst,
    output          axi_wvalid,
    input           axi_wready,
    output [255:0]  axi_wdata,
    output [31:0]   axi_wstrb,
    output          axi_wlast,
    input           axi_bvalid,
    output          axi_bready,
    input  [5:0]    axi_bid,
    input  [1:0]    axi_bresp,
    output          axi_arvalid,
    input           axi_arready,
    output [5:0]    axi_arid,
    output [31:0]   axi_araddr,
    output [7:0]    axi_arlen,
    output [2:0]    axi_arsize,
    output [1:0]    axi_arburst,
    input           axi_rvalid,
    output          axi_rready,
    input  [5:0]    axi_rid,
    input  [255:0]  axi_rdata,
    input  [1:0]    axi_rresp,
    input           axi_rlast
);

    axi_llc_axi_bridge #(
        .ADDR_BITS(32),
        .ID_BITS(6),
        .LINE_BYTES(64),
        .LINE_BITS(512),
        .AXI_ID_BITS(6),
        .AXI_DATA_BYTES(32),
        .AXI_DATA_BITS(256),
        .AXI_STRB_BITS(32),
        .READ_RESP_BYTES(64),
        .READ_RESP_BITS(512),
        .READ_PENDING_COUNT(32),
        .WRITE_PENDING_COUNT(32)
    ) u_bridge (
        .clk(clk),
        .rst_n(rst_n),
        .cache_req_valid(cache_req_valid),
        .cache_req_ready(cache_req_ready),
        .cache_req_write(cache_req_write),
        .cache_req_addr(cache_req_addr),
        .cache_req_id(cache_req_id),
        .cache_req_size(cache_req_size),
        .cache_req_wdata(cache_req_wdata),
        .cache_req_wstrb(cache_req_wstrb),
        .cache_resp_valid(cache_resp_valid),
        .cache_resp_ready(cache_resp_ready),
        .cache_resp_rdata(cache_resp_rdata),
        .cache_resp_id(cache_resp_id),
        .cache_resp_code(cache_resp_code),
        .bypass_req_valid(bypass_req_valid),
        .bypass_req_ready(bypass_req_ready),
        .bypass_req_write(bypass_req_write),
        .bypass_req_addr(bypass_req_addr),
        .bypass_req_id(bypass_req_id),
        .bypass_req_size(bypass_req_size),
        .bypass_req_mode2_ddr_aligned(bypass_req_mode2_ddr_aligned),
        .bypass_req_wdata(bypass_req_wdata),
        .bypass_req_wstrb(bypass_req_wstrb),
        .bypass_resp_valid(bypass_resp_valid),
        .bypass_resp_ready(bypass_resp_ready),
        .bypass_resp_rdata(bypass_resp_rdata),
        .bypass_resp_id(bypass_resp_id),
        .bypass_resp_code(bypass_resp_code),
        .axi_awvalid(axi_awvalid),
        .axi_awready(axi_awready),
        .axi_awid(axi_awid),
        .axi_awaddr(axi_awaddr),
        .axi_awlen(axi_awlen),
        .axi_awsize(axi_awsize),
        .axi_awburst(axi_awburst),
        .axi_wvalid(axi_wvalid),
        .axi_wready(axi_wready),
        .axi_wdata(axi_wdata),
        .axi_wstrb(axi_wstrb),
        .axi_wlast(axi_wlast),
        .axi_bvalid(axi_bvalid),
        .axi_bready(axi_bready),
        .axi_bid(axi_bid),
        .axi_bresp(axi_bresp),
        .axi_arvalid(axi_arvalid),
        .axi_arready(axi_arready),
        .axi_arid(axi_arid),
        .axi_araddr(axi_araddr),
        .axi_arlen(axi_arlen),
        .axi_arsize(axi_arsize),
        .axi_arburst(axi_arburst),
        .axi_rvalid(axi_rvalid),
        .axi_rready(axi_rready),
        .axi_rid(axi_rid),
        .axi_rdata(axi_rdata),
        .axi_rresp(axi_rresp),
        .axi_rlast(axi_rlast)
    );

endmodule
